[package]
name = "valhalla_registry"
version = "0.1.0"
description = "On-chain ownership and treasury registry for Valhalla"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "valhalla_registry"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
